server:
  port: 9091
  

#jdbc:mysql://localhost:3306/springmicroservicedemo?createDatabaseIfNotExist=true         
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prov-customer
    username: provapiuser
    password: provapiuser1 
    driver-class-name: com.mysql.cj.jdbc.Driver

#If camel case is used in the model field, then it will create using _ . This can be avoided with this property    
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
          

