server:
  port: 9091
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pradeeppatro/spring-cloud-config-store
          #username: xyz
          #passphrase: abc 
          search-paths:
          - '*service' 
