server:
  port: 9090
  
management:
  endpoints:
    web:
      exposure:
        include:
         '*'

#jdbc:mysql://localhost:3306/springmicroservicedemo?createDatabaseIfNotExist=true         
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ticketbookingsystem
    username: ticketsysusr
    password: ticketsysusr 
    driver-class-name: com.mysql.cj.jdbc.Driver

#If camel case is used in the model field, then it will create using _ . This can be avoided with this property    
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
        
  
