server:
  port: 8282
  
#spring:
#  security:
#    user:
#      name: pradeep
#      password: pradeep
#      roles: ADMIN, USER
      
#security:
 # oauth2:
  #  client:
   #   id: mobile
    #  client-secret: pin
     # access-token-validity-seconds: 3600
     # authorized-grant-types: refresh_token, authorization_code, password, client_credentials
      #scope: READ, WRITE
    #authorization:
     # check-token-access: permitAll  
      
        
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ticketbookingsystem
    username: ticketsysusr
    password: ticketsysusr
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace